server:
  port: ${PORT:0}
spring:
  application:
    name: "msvc-products"
  datasource:
    url: "jdbc:mysql://localhost:3306/db_springboot_cloud"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}
    prefer-ip-address: true



