server:
  port: 8005
spring:
  application:
    name: "msvc-products"
  datasource:
    url: "jdbc:mysql://localhost:3306/db_springboot_cloud"
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
